INSERT INTO USERS(ID, USER_FIRST_NAME, USER_SURNAME, CREATED_BY, CREATED_AT, MODIFIED_BY, MODIFIED_AT) VALUES(1, 'Ambrose', 'Bourg', 'tester', CURRENT_DATE, 'tester', CURRENT_DATE);
INSERT INTO USERS(ID, USER_FIRST_NAME, USER_SURNAME, CREATED_BY, CREATED_AT, MODIFIED_BY, MODIFIED_AT) VALUES(2, 'Ian', 'Jennings', 'tester', CURRENT_DATE, 'tester', CURRENT_DATE);

INSERT INTO TASKS(ID, TASK_DESCRIPTION, TASK_NAME, TASK_STATUS, USER_ID, CREATED_BY, CREATED_AT, MODIFIED_BY, MODIFIED_AT) VALUES(1, '', 'Dummy Task', 'COMPLETED', 1, 'tester', CURRENT_DATE, 'tester', CURRENT_DATE);
INSERT INTO TASKS(ID, TASK_DESCRIPTION, TASK_NAME, TASK_STATUS, USER_ID, CREATED_BY, CREATED_AT, MODIFIED_BY, MODIFIED_AT) VALUES(2, '', 'Dummy Task', 'COMPLETED', 1, 'tester', CURRENT_DATE, 'tester', CURRENT_DATE);